---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ template "webhook-inject-sidecar.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded   
  name: {{ template "webhook-inject-sidecar.fullname" . }}-admission-create
  labels:
    app: {{ template "webhook-inject-sidecar.name" $ }}-admission-create
{{ include "webhook-inject-sidecar.labels" $ | indent 4 }}
spec:
  template:
    metadata:
      name:  {{ template "webhook-inject-sidecar.fullname" . }}-admission-create
      labels:
        app: {{ template "webhook-inject-sidecar.name" $ }}-admission-create
{{ include "webhook-inject-sidecar.labels" $ | indent 8 }}
    spec:
      containers:
        - name: create
          image: {{ .Values.imageCert }}
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host={{ template "webhook-inject-sidecar.fullname" . }}-operator,{{ template "webhook-inject-sidecar.fullname" . }}-operator.{{- template "webhook-inject-sidecar.namespace" . }}.svc
            - --namespace={{- template "webhook-inject-sidecar.namespace" . }}
            - --secret-name={{ template "webhook-inject-sidecar.fullname" . }}-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "webhook-inject-sidecar.fullname" . }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
