---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ template "webhook-inject-sidecar.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  name: {{ template "webhook-inject-sidecar.fullname" . }}-admission
  labels:
    app: {{ template "webhook-inject-sidecar.name" $ }}-admission
{{ include "webhook-inject-sidecar.labels" $ | indent 4 }}
