---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "webhook-inject-sidecar.fullname" . }}-admission
  labels:
    app: {{ template "webhook-inject-sidecar.name" $ }}-admission
{{ include "webhook-inject-sidecar.labels" $ | indent 4 }}
webhooks:
  - name: {{ template "webhook-inject-sidecar.fullname" . }}rulemutate.{{ template "webhook-inject-sidecar.namespace" . }}.com
    failurePolicy: Ignore
    # rules:
    #   - apiGroups:
    #       - webhookmini.com
    #     apiVersions:
    #       - "*"
    #     resources:
    #       - prometheusrules
    #     operations:
    #       - CREATE
    #       - UPDATE
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        webhook-mini: enabled
    clientConfig:
      service:
        namespace: {{ template "webhook-inject-sidecar.namespace" . }}
        name: {{ template "webhook-inject-sidecar.fullname" . }}-operator
        path: /mutate
    timeoutSeconds: 10
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
